travis:
  secure:
    BINSTAR_TOKEN: OQDQqW52vm2ZfD9ZIZDK96w64egrfY9UO8WyHbNhtRKkZKhfOWQ8s+3JbjYBY9g2xij6gapSXe8CfCuTunh5qsp2y4KVdnqx4QOlajtIKqFxhuh2UdXpt5w3fuODeoIjUGlsP2qL4qX6aWtILipV6iaWOO/6zJ80u0NuCbih/y2jD3Y05bYjuRddd/OYpphfMg6PbGLzvZidC7QJexijr2/PehOC4rEiqGXbUaEia03BHvudEgexQrxSrmccNZekAJdD2mmN0Y4GXfcwclmuhyaD/mJtd+4B2bLaoY7zw4nzAe9/AmZF1BDisqeDwNBQtr++VA6mErbnr2zTHVapbwrjQnK93tVgJIueDpoDE7p2J8OXJnrf/Pxalezqvjhk/HN2TTcqcS18ztzegwSL08rVkng6r/o1oQiDxJQkkPMC9VCBNKbW4xfK/MQ68wJN4N/dLj8upi7xr0ActD+JglNiQ9J7Rgqo88sKd5BWTBop9vZW6t1+iTPSVO5dECjPQxRPAtQs3MJCrzKl+jmM/51eyJe0KQsdoGACOCoc7wNgkn5/Nuy+qe9+8X+vAYT+GF8m9374q9XMYQY7uW2DA7eOy8E36C1meuDU0q8ZwcXrfmq8FaQ/hAltC37KQCRQSBWITC2F+c4MlxQFgBeAzxt/HWEI+v7KeKePkaOFpog=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
