travis:
  secure:
    BINSTAR_TOKEN: Q83BGENWZb6b2BZbnaM8XfAR3bgrZKse1dSAK2OdjMr57mkc6ZBvFmx8hGVTaZsxNOwAsl43OQpD9Q34FYImUhMDD9jUPu4EiSYFVf/hiwbavBIGKz8MWTAximMarOnWQTt+QGo0V2sTX23OtGvDghKXIo8akqP2x5DBrxWzWnYX1KsvkWqgaMfZv2OmMON7l9vy8rPYbeBo/ORHeogtmLzsXoVF2LAw1EdxGu7/uebXAz/c9trc0IHIY+CprrxRMioguZdu5EdUdfj9ZT2NMUXpZsZVP5gS82bR4pRYvlEzmjBDVzRIVmMpiIbnEdPQpV22J3jbKRQMJwHOBgGxn6d6Qm7nORLE9uDQfHhlTFBoUDwE1tBM5hI1tegvstCcvPWYEs5ABHO1fgEpDRUtqCSi8eiCcEyWc2drAKeaZzNHMX2hsQmAl7H+hS69120WWSuQBieE4u9Ln/b6FuOs8CGMCWfnq2san/MCw1QWKlr2DcIqAtrg1KkKT6DDUjO+SHmORcBgvAUyoGinXIyOlMzXqOl8IQIYHXi/Yv0pEVFQPGC05IC5cNVja/cEN9PJJSsosBaqID5IVCjqBDBo4g3t0HnLnnLdJX9TbD0ZDij1vb5HySziuzhh9FkROhMs/zUYdO6/zCEAreA13+dWWvbZ5WiSIyNEz6+D+sIdsc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
